### ISSUE TITLE
Simulating bigger boxes

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/acemd_issues#3] opened 2016-05-31 12:06 UTC
ACEMD limits dimensions to 256 AA. Would be nice if the limit could be increased considering growing GPU memories (if that was the issue). I attach the system [1hci.zip](https://github.com/Acellera/acemd_issues/files/291007/1hci.zip).

![vmdscene](https://cloud.githubusercontent.com/assets/7935362/15673727/ce5fb5a2-2738-11e6-823b-935a94552ba5.png)

**Comment by giadefa** [comment] 2016-05-31 12:18
I think the problem is FFT

On 31 May 2016 at 14:06, Stefan <notifications@github.com> wrote:

> ACEMD limits dimensions to 256 AA. Would be nice if the limit could be
> increased considering growing GPU memories (if that was the issue). I
> attach the system 1hci.zip
> <https://github.com/Acellera/acemd_issues/files/291007/1hci.zip>.
>
> [image: vmdscene]
> <https://cloud.githubusercontent.com/assets/7935362/15673727/ce5fb5a2-2738-11e6-823b-935a94552ba5.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/acemd_issues/issues/3>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHaqOqc_I_tDmWQHe4d4bUePQ9x6YF91ks5qHCRDgaJpZM4IqdgG>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by mj-harvey** [comment] 2016-11-07 15:49
I'm going to close this as the current version isn't going to be enhanced, and this probably wont be a limitation of the next version

**Closed by mj-harvey** 2016-11-07 15:49 UTC
Labels: enhancement
