### ISSUE TITLE
equilibration stops

### ISSUE THREAD

**Issue by slovera** [Acellera/acemd_issues#16] opened 2016-10-26 12:37 UTC
Hi,

I am running using acemd version 2016.6.21 on K40. The system has about 60000 atoms.
Equilibration was running fine till when memory warning arose followed by another error message ( please see log attached). 
[log.txt](https://github.com/Acellera/acemd_issues/files/553213/log.txt)

Thank you!

**Comment by slovera** [comment] 2016-10-27 10:44
cell dimension of initial structure checked using get_celldimension.vmd (89.40800094604492 90.79100036621094 90.91400146484375) are corresponding to the ones in the acemd input file (89.38600158691406 90.78199768066406 90.91400146484375).

**Comment by mj-harvey** [comment] 2016-11-07 15:50
@slovera the get_celldimension is probably giviing the full linear extent of the system. That might be misleadingly large. Turn on periodicity in the VMD view with that box dimension set and I epxect you'll see gaps between the images.

**Comment by j3mdamas** [comment] 2016-11-07 16:31
Sílvia found a solution, with one of the axis being too large. I don't know
if it was any bug of the htmd building process, as I would never commands
to reproduce it.

**Comment by j3mdamas** [comment] 2016-11-22 14:29
Since there was no reproduction of this problem, I'll close this. @slovera, if you have a reproducible case where this happens, and is due to htmd, please post it.

**Closed by j3mdamas** 2016-11-22 14:29 UTC
